### ISSUE TITLE
Very Large Data Base (VLDB) conference not retrieved in the searchbox

### ISSUE THREAD

**Issue by valeriocos** [SOM-Research/metaScience#53]
The conference VLDB is not found when using the search box (on the landing page). However if the source id of the conference is passed to the servlet venue (http://som-research.uoc.edu/tools/metaScience/venue.html?id=VLDB), the corresponding data is correctly shown.

**Comment by jlcanovas** [comment]
Curiosly enough, when entering "very large data" in the search box the only result is "VLDB PHD WORKSHOP - Very Large Data Bases Conference" (linking to http://som-research.uoc.edu/tools/metaScience/venue.html?id=VLDB%20PhD%20Workshop), which looks as an error (workshop vs. conference name in the entry).

**Comment by jlcanovas** [comment]
Checking the database entries including "very large" in the title, we have these two results:

![screenshot](https://cloud.githubusercontent.com/assets/1996760/9631113/1181d59e-517f-11e5-9d39-67472bcf19da.PNG)

It seems to be an error in the first row (it is a workshop but it is classified as conference). That information is obtained by web scraping ([here](https://github.com/SOM-Research/metaScience/blob/dc82ccc1949fe1a54507a00f86c0527ca6dedc24/extractor/update_title_conference.py) for titles and [here](https://github.com/SOM-Research/metaScience/blob/dc82ccc1949fe1a54507a00f86c0527ca6dedc24/extractor/update_type_conference.py) for types). 

Maybe line the problem is [this line](https://github.com/SOM-Research/metaScience/blob/dc82ccc1949fe1a54507a00f86c0527ca6dedc24/extractor/update_title_conference.py#L33) of the script for titles? Or maybe being a phd workshop the title in DBLP is actually the name of the conference.

**Comment by jlcanovas** [comment]
Re-generating the aux tables in a test environment.

**Comment by jlcanovas** [comment]
Table regenerated and deployed. Related PR is now aligned.
